ui: mocha-bdd
html: test/fixtures/template.html
scripts:
  - build/in-viewport.min.js
browsers:
  - name: chrome
    version: 34..latest
  - name: firefox
    version: 28..latest
  - name: ie
    version: 8..latest
  - name: iphone
    version: 5.0..latest
  - name: ipad
    version: 5.0..latest