ui: mocha-bdd
html: test/fixtures/template.html
scripts:
  - in-viewport.js
browsers:
  - name: chrome
    version: 29..latest
  - name: firefox
    version: 24..latest
  - name: ie
    version: 8..latest
  - name: iphone
    version: 5.0..latest
  - name: ipad
    version: 5.0..latest